# Generated by Django 5.1.4 on 2025-01-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
