# Generated by Django 5.1.4 on 2025-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_custuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='custuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='custuser',
            old_name='is_admin',
            new_name='is_hr',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='custuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
